# Generated by Django 4.2.15 on 2024-09-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("progress_percentage", models.IntegerField()),
                ("amount_raised", models.DecimalField(decimal_places=2, max_digits=10)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
