# Generated by Django 4.2.15 on 2024-09-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("nepal", "Nepal"),
                            ("netherlands", "Netherlands"),
                            ("world", "World"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=255)),
                ("facebook_url", models.URLField(blank=True, max_length=255)),
                ("twitter_url", models.URLField(blank=True, max_length=255)),
                ("linkedin_url", models.URLField(blank=True, max_length=255)),
            ],
        ),
    ]
