# Generated by Django 5.1 on 2024-09-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='image_url',
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
    ]
